Ödev2'yi içeren kod dosyası.
VB10/Dart-Language-Full-Course pull request #4
Opened 2024-07-23 13:41 UTC by CrpoBeginner

2024-07-23 16:07 UTC, VB10 requested changes
sanau ufak eklemeler yaptim go fix

2024-07-23 16:07 UTC, VB10 commented on user_advance.dart
> +  const String BankName2 = "Vb Bank";
veriable name buyuk harfle olmaz ona dikkat edelim

2024-07-23 16:07 UTC, VB10 commented on user_advance.dart
> +  const double user1parasi = 100.00;
user1parasi camel case romatlamaya uymuyor dikkat edleim

2024-07-23 16:07 UTC, VB10 commented on user_advance.dart
> +  final String workplaceName = "MertHaliSaha";
camelcase

2024-07-23 16:07 UTC, VB10 commented on user_advance.dart
> +  int sum = musteri1Cap + musteri2Cap;
sum degil misal customerTotalCap

2024-07-23 16:07 UTC, VB10 commented on user_advance.dart
> +  const String BankName = "vbbank";
buyuk harfle veriable name olmaz

2024-07-24 14:17 UTC, CrpoBeginner commented on user_advance.dart
> +  int sum = musteri1Cap + musteri2Cap;
Tüm belirttiğiniz commentlere uyarak düzenledim,teşekkür ederim hocam.

2024-07-24 15:14 UTC, closed without merging